# Generated by Django 4.1.3 on 2022-11-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('subscriber_count', models.PositiveIntegerField(verbose_name='Количество подписчиков')),
                ('completed_order_count', models.PositiveIntegerField(verbose_name='Количество выполненных заказов')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('any', 'Любая'), ('sport', 'Спорт'), ('art', 'Рисование')], default='any', max_length=255, verbose_name='Категория')),
                ('subscriber_count', models.CharField(choices=[('0-1000', 'От 0 до 1000'), ('1000-2000', 'От 1000 до 2000')], default='0-1000', max_length=255, verbose_name='Количество подписчиков')),
                ('last_activity', models.CharField(choices=[('recently', 'Недавно')], default='recently', max_length=255, verbose_name='Последняя активность')),
                ('result', models.CharField(choices=[('any', 'Любой')], default='any', max_length=255, verbose_name='Результат')),
                ('rating', models.CharField(choices=[('0-1000', 'От 0 до 1000'), ('1000-2000', 'От 1000 до 2000')], default='0-1000', max_length=255, verbose_name='Рейтинг')),
            ],
        ),
    ]
